export const REPORTS = [
    {
      title: "Heavy Traffic on Hosur Road",
      description: "Traffic jam between Silk Board and Electronic City. Avoid route.",
      category: "traffic",
      severity: "high",
      lat: 12.9121,
      lon: 77.6226,
      confidence: 87,
      sources: 5,
      timestamp: "3 min ago",
      image: "",
    },
    {
      title: "Flooded Street at Koramangala 4th Block",
      description: "Heavy rainfall has caused waterlogging near Forum Mall.",
      category: "weather",
      severity: "medium",
      lat: 12.934533,
      lon: 77.615673,
      confidence: 65,
      sources: 3,
      timestamp: "10 min ago",
      image: "",
    },
    {
      title: "Power Outage in Indiranagar",
      description: "Scheduled maintenance, power expected to resume by 2 PM.",
      category: "infrastructure",
      severity: "low",
      lat: 12.971891,
      lon: 77.641151,
      confidence: 92,
      sources: 2,
      timestamp: "5 min ago",
      image: "",
    },
    {
      title: "Metro Delay at MG Road Station",
      description: "Technical issue, trains delayed by 20 min.",
      category: "infrastructure",
      severity: "medium",
      lat: 12.9751,
      lon: 77.6036,
      confidence: 75,
      sources: 4,
      timestamp: "15 min ago",
      image: "",
    },
    {
      title: "Accident on Outer Ring Road",
      description: "Multi-vehicle collision near Marathahalli. Emergency services on site.",
      category: "emergency",
      severity: "critical",
      lat: 12.9561,
      lon: 77.7019,
      confidence: 80,
      sources: 6,
      timestamp: "8 min ago",
      image: "",
    },
    {
      title: "Event: Farmers Market at Lalbagh",
      description: "Local farmers market open till 7 PM.",
      category: "event",
      severity: "low",
      lat: 12.9507,
      lon: 77.5848,
      confidence: 99,
      sources: 1,
      timestamp: "Now",
      image: "",
    },
    {
      title: "Roadwork at Bannerghatta Road",
      description: "Lane closed for repairs near Meenakshi Mall.",
      category: "infrastructure",
      severity: "medium",
      lat: 12.891,
      lon: 77.603,
      confidence: 70,
      sources: 2,
      timestamp: "12 min ago",
      image: "",
    },
    {
      title: "Rain Alert: Richmond Town",
      description: "Rain expected in next 30 minutes. Drive carefully.",
      category: "weather",
      severity: "low",
      lat: 12.9634,
      lon: 77.5971,
      confidence: 60,
      sources: 1,
      timestamp: "6 min ago",
      image: "",
    },
    {
      title: "Fire Alert in Whitefield",
      description: "Small fire at ITPL campus, fire brigade on site.",
      category: "emergency",
      severity: "high",
      lat: 12.9877,
      lon: 77.7287,
      confidence: 85,
      sources: 7,
      timestamp: "4 min ago",
      image: "",
    },
    {
      title: "Traffic Update: Yeshwanthpur",
      description: "Traffic slow due to market crowd. Alternate route advised.",
      category: "traffic",
      severity: "medium",
      lat: 13.0285,
      lon: 77.5552,
      confidence: 68,
      sources: 3,
      timestamp: "9 min ago",
      image: "",
    },
  ];